// <auto-generated />
using System;
using EnumAsDiscriminator.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.ValueGeneration;

namespace EnumAsDiscriminator.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview3-32064")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnumAsDiscriminator.API.Base", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Direction");

                    b.HasKey("Id");

                    b.ToTable("Base");

                    b.HasDiscriminator<int>("Direction");
                });

            modelBuilder.Entity("EnumAsDiscriminator.API.Left", b =>
                {
                    b.HasBaseType("EnumAsDiscriminator.API.Base");

                    b.Property<int>("Number")
                        .HasColumnName("Number");

                    b.ToTable("Left");

                    b.HasDiscriminator().HasValue(Direction.Left);
                });

            modelBuilder.Entity("EnumAsDiscriminator.API.Right", b =>
                {
                    b.HasBaseType("EnumAsDiscriminator.API.Base");

                    b.Property<int>("Number")
                        .HasColumnName("Number");

                    b.ToTable("Right");

                    b.HasDiscriminator().HasValue(Direction.Right);
                });
#pragma warning restore 612, 618
        }
    }
}
